/**
 * Paths that show the custom Montfort Google reviews carousel at end of content
 * (same pages that originally embedded ReputationHub on HTTrack).
 * Reviews render via PageShell, matching the original placement.
 * Home (`/`) is excluded — it uses a mid-page ReviewsSection after Services.
 */
export const ORIGINAL_REVIEW_PATHS: ReadonlySet<string> = new Set([
  "/2-family-house-for-sale-nyc",
  "/3-family-house-for-sale-nyc",
  "/4-family-house-for-sale-nyc",
  "/about-us",
  "/bedford-stuyvesant",
  "/bedford-stuyvesant-brownstones-2",
  "/bedford-stuyvesant-co-ops-2",
  "/bedford-stuyvesant-co-ownership",
  "/bedford-stuyvesant-condos-2",
  "/bedford-stuyvesant-sros-2",
  "/brooklyn-heights",
  "/brooklyn-heights-co-ops-3",
  "/brooklyn-heights-condos-3",
  "/brooklyn-heights-townhouses-2",
  "/buying-a-brownstone-in-nyc",
  "/buying-a-condo-in-nyc",
  "/buying-sro-in-nyc",
  "/chelsea",
  "/chelsea-co-ops-2",
  "/chelsea-townhouses",
  "/co-ownership-buying-in-nyc",
  "/crown-heights",
  "/crown-heights-brownstones-2",
  "/crown-heights-co-ops-2",
  "/crown-heights-co-ownership-2",
  "/crown-heights-condos-2",
  "/crown-heights-sros-3",
  "/downstone-brooklyn-co-ops",
  "/downtown-brooklyn",
  "/downtown-brooklyn-condos-2",
  "/dumbo",
  "/dumbo-co-ops-2",
  "/dumbo-condos",
  "/harlem",
  "/harlem-brownstones",
  "/harlem-co-ownership",
  "/harlem-condos",
  "/harlem-co-ops",
  "/harlem-sros",
  "/home-valuation",
  "/mortgage-calculator",
  "/neighborhoods",
  "/nyc-brownstone-free-home-valuation",
  "/nyc-brownstone-mortgages",
  "/nyc-buyers-agent-service",
  "/nyc-co-op-free-home-valuation",
  "/nyc-condo-free-home-valuation",
  "/nyc-first-time-home-buyer-mortages",
  "/nyc-listing-agent-service",
  "/nyc-multifamily-real-estate-agent-service",
  "/nyc-sro-free-home-valuation",
  "/nyc-sro-mortgages",
  "/park-slope-brownstone-2",
  "/park-slope-condo-2",
  "/park-slope-coops",
  "/selling-brownstones-in-nyc",
  "/selling-co-ops-in-nyc",
  "/selling-condos-in-nyc",
  "/selling-probate-properties-in-nyc",
  "/selling-sros-in-nyc",
  "/services",
  "/upper-east-side",
  "/upper-east-side-co-ops",
  "/upper-east-side-condos",
  "/upper-east-side-townhouses",
  "/upper-west-side",
  "/upper-west-side-co-ops-2",
  "/upper-west-side-condos",
  "/upper-west-side-townhouses",
  "/williamsburg",
  "/williamsburg-brownstones-2",
  "/williamsburg-co-ownership",
  "/williamsburg-condos",
]);

export function pathHadOriginalReviews(pathname: string): boolean {
  const normalized = pathname.replace(/\/+$/, "") || "/";
  return ORIGINAL_REVIEW_PATHS.has(normalized);
}
