import ContactSection from "../shared/ContactSection";
import ResourcesSection from "../shared/ResourcesSection";

export default function TwoFamilyContent() {
  return (
    <>
      <section data-screen-label="Service hero" style={{ position: "relative", background: "#F5EECB", borderBottom: "1px solid #E0D9B8", overflow: "hidden", padding: "80px 64px 90px" }}>
        <div style={{ position: "absolute", top: -150, right: -160, width: 560, height: 560, borderRadius: "50%", border: "1px solid rgba(201,138,44,0.2)" }}></div>
        <div style={{ position: "relative", zIndex: "2", maxWidth: 1440, margin: "0 auto", display: "grid", gridTemplateColumns: "1.02fr 0.98fr", gap: "72px", alignItems: "center" }}>
         <div data-reveal="">
          <div style={{ display: "inline-flex", alignItems: "center", gap: "10px", fontSize: 11, fontWeight: "700", letterSpacing: "0.16em", textTransform: "uppercase", color: "#8A7B4E" }}><a href="/nyc-multifamily-real-estate-agent-service/" style={{ color: "#8A7B4E" }}>Multifamily</a> <span style={{ opacity: ".5" }}>/</span> <span style={{ color: "#C98A2C" }}>2 Family House</span></div>
          <h1 style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 58, lineHeight: "1.05", letterSpacing: "-0.02em", color: "#0F1729", margin: "18px 0 0", textWrap: "pretty" }}>2 Family Homes<br />for Sale in NYC</h1>
          <p style={{ fontSize: 19, lineHeight: "1.7", color: "#3B4C5E", margin: "22px 0 0", maxWidth: 560, textWrap: "pretty" }}>We'll help you make a smart <strong style={{ fontWeight: "700", color: "#0F1729" }}>two-family home purchase</strong>, maximizing rental income potential while avoiding costly maintenance, legal, and compliance issues.</p>
          <div style={{ display: "flex", flexWrap: "wrap", gap: "14px", marginTop: 34 }}>
           <a href="https://calendly.com/montfort" style={{ display: "inline-flex", alignItems: "center", justifyContent: "center", background: "#113B5F", color: "#F9F6E6", fontSize: 15, fontWeight: "800", letterSpacing: "0.05em", textTransform: "uppercase", borderRadius: "100px", padding: "18px 34px", minHeight: 56 }} {...{ "style-hover": "background:#C98A2C; color:#0F1729" }}>Book Now</a>
           <a href="tel:646-970-1078" style={{ display: "inline-flex", alignItems: "center", justifyContent: "center", border: "2px solid #113B5F", color: "#113B5F", fontSize: 15, fontWeight: "800", letterSpacing: "0.03em", borderRadius: "100px", padding: "16px 30px", minHeight: 56 }} {...{ "style-hover": "background:#113B5F; color:#F9F6E6" }}>(646) 970-1078</a>
          </div>
          <div style={{ marginTop: 38, paddingTop: 26, borderTop: "1px solid #D9CFA6" }}>
           <div style={{ fontSize: "11.5px", fontWeight: "700", letterSpacing: "0.18em", textTransform: "uppercase", color: "#8A7B4E" }}>Serving most locations in</div>
           <div style={{ display: "grid", gridTemplateColumns: "repeat(3,minmax(0,1fr))", gap: "14px 40px", marginTop: 18 }}>
            <a href="/harlem/" style={{ fontSize: "15.5px", fontWeight: "600", color: "#0F1729", textWrap: "pretty" }} {...{ "style-hover": "color:#C98A2C" }}>Harlem</a><a href="/upper-west-side/" style={{ fontSize: "15.5px", fontWeight: "600", color: "#0F1729", textWrap: "pretty" }} {...{ "style-hover": "color:#C98A2C" }}>Upper West Side</a><a href="/chelsea/" style={{ fontSize: "15.5px", fontWeight: "600", color: "#0F1729", textWrap: "pretty" }} {...{ "style-hover": "color:#C98A2C" }}>Chelsea</a><a href="/brooklyn-heights/" style={{ fontSize: "15.5px", fontWeight: "600", color: "#0F1729", textWrap: "pretty" }} {...{ "style-hover": "color:#C98A2C" }}>Brooklyn Heights</a><a href="/williamsburg/" style={{ fontSize: "15.5px", fontWeight: "600", color: "#0F1729", textWrap: "pretty" }} {...{ "style-hover": "color:#C98A2C" }}>Williamsburg</a><a href="/bedford-stuyvesant/" style={{ fontSize: "15.5px", fontWeight: "600", color: "#0F1729", textWrap: "pretty" }} {...{ "style-hover": "color:#C98A2C" }}>Bedford-Stuyvesant</a>
            <a href="/neighborhoods/" style={{ fontSize: "15.5px", fontWeight: "700", color: "#113B5F", display: "inline-flex", alignItems: "center", gap: "8px" }} {...{ "style-hover": "color:#C98A2C" }}>And more <span style={{ color: "#C98A2C" }}>→</span></a>
           </div>
          </div>
         </div>
         <div data-reveal="" style={{ position: "relative" }}>
          <div style={{ position: "relative", borderRadius: "16px", overflow: "hidden", aspectRatio: "5/4", background: "#E0D9B8", border: "6px solid #FFFFFF", boxShadow: "0 40px 90px rgba(17,59,95,0.28)" }}>
           <img src="/redesign-assets/services/2-family-house-for-sale-nyc.webp" alt="2 family house for sale NYC" style={{ position: "absolute", inset: 0, width: "100%", height: "100%", objectFit: "cover", display: "block" }} />
          </div>
          <div style={{ position: "absolute", right: -14, bottom: -22, display: "inline-flex", alignItems: "center", gap: "18px", background: "#FFFFFF", border: "1px solid rgba(201,138,44,0.55)", borderRadius: "16px", boxShadow: "0 22px 48px rgba(17,59,95,0.28)", padding: "18px 26px", whiteSpace: "nowrap" }}>
           <img src="https://www.google.com/images/branding/googleg/1x/googleg_standard_color_128dp.png" alt="Google" style={{ flex: "0 0 auto", width: 50, height: 50, display: "block" }} />
           <div style={{ display: "flex", flexDirection: "column", gap: "4px" }}>
            <span style={{ fontSize: 19, fontWeight: "700", lineHeight: "1", letterSpacing: "-0.01em", color: "#0F1729" }}>Google Rating</span>
            <div style={{ display: "flex", alignItems: "center", gap: "9px" }}><span style={{ fontSize: 23, fontWeight: "700", lineHeight: "1", color: "#C98A2C" }}>5.0</span><span style={{ color: "#F5A623", fontSize: 19, letterSpacing: "0.08em", lineHeight: "1" }}>★★★★★</span></div>
            <span style={{ fontSize: 14, lineHeight: "1.3", color: "#0F1729" }}>Over <strong style={{ fontWeight: "700" }}>57 Reviews</strong></span>
           </div>
          </div>
         </div>
        </div>
       </section>
       <section data-screen-label="Client promises" style={{ background: "#F9F6E6", borderBottom: "1px solid #E0D9B8", padding: "36px 64px" }}>
        <div style={{ maxWidth: 1440, margin: "0 auto", display: "grid", gridTemplateColumns: "repeat(3,minmax(0,1fr))", gap: "48px" }}>
         <div data-reveal="" style={{ display: "flex", alignItems: "flex-start", gap: "18px" }}><span style={{ flex: "0 0 auto", width: 46, height: 46, borderRadius: "100px", background: "#C98A2C", display: "flex", alignItems: "center", justifyContent: "center" }}><svg width="22" height="22" viewBox="0 0 24 24" fill="none"><path d="M6 12.5l3.5 3.5L18 7.5" stroke="#0F1729" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round"></path></svg></span><div><div style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 18, letterSpacing: "0.02em", textTransform: "uppercase", color: "#0F1729" }}>Smooth Transaction</div><p style={{ fontSize: 16, lineHeight: "1.65", color: "#3B4C5E", margin: "8px 0 0", textWrap: "pretty" }}>With limited risk throughout the buying process.</p></div></div><div data-reveal="" style={{ display: "flex", alignItems: "flex-start", gap: "18px" }}><span style={{ flex: "0 0 auto", width: 46, height: 46, borderRadius: "100px", background: "#C98A2C", display: "flex", alignItems: "center", justifyContent: "center" }}><svg width="22" height="22" viewBox="0 0 24 24" fill="none"><path d="M6 12.5l3.5 3.5L18 7.5" stroke="#0F1729" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round"></path></svg></span><div><div style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 18, letterSpacing: "0.02em", textTransform: "uppercase", color: "#0F1729" }}>No Pressure</div><p style={{ fontSize: 16, lineHeight: "1.65", color: "#3B4C5E", margin: "8px 0 0", textWrap: "pretty" }}>No pressure to overpay or purchase within a specific timeframe.</p></div></div><div data-reveal="" style={{ display: "flex", alignItems: "flex-start", gap: "18px" }}><span style={{ flex: "0 0 auto", width: 46, height: 46, borderRadius: "100px", background: "#C98A2C", display: "flex", alignItems: "center", justifyContent: "center" }}><svg width="22" height="22" viewBox="0 0 24 24" fill="none"><path d="M6 12.5l3.5 3.5L18 7.5" stroke="#0F1729" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round"></path></svg></span><div><div style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 18, letterSpacing: "0.02em", textTransform: "uppercase", color: "#0F1729" }}>Ongoing Support</div><p style={{ fontSize: 16, lineHeight: "1.65", color: "#3B4C5E", margin: "8px 0 0", textWrap: "pretty" }}>A dedicated team that remains available even after the transaction is complete.</p></div></div>
        </div>
       </section>
       <section data-screen-label="Guide" style={{ background: "#fff", padding: "100px 64px", borderBottom: "1px solid #E0D9B8" }}>
        <div style={{ maxWidth: 880, margin: "0 auto" }}>
         <div data-reveal="">
          <div style={{ fontSize: "11.5px", fontWeight: "700", letterSpacing: "0.18em", textTransform: "uppercase", color: "#C98A2C" }}>Buyer's Guide</div>
          <h1 style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 42, lineHeight: "1.16", letterSpacing: "-0.015em", color: "#0F1729", margin: "14px 0 0", textWrap: "pretty" }}>2 Family House for Sale NYC: your complete buyer's guide</h1>
          <div style={{ width: 72, height: 3, background: "#C98A2C", margin: "22px 0 0" }}></div>
    
          <p style={{ fontSize: 17, lineHeight: "1.85", color: "#3B4C5E", margin: "16px 0 0", textWrap: "pretty" }}>If you're searching for a 2 family house for sale in NYC, you're not just buying a home, you're evaluating an income-producing asset in one of the most complex real estate markets in the country. The difference between a smart purchase and a costly mistake often comes down to understanding legal configuration, realistic rental income, financing options, and the dozens of details that don't show up in a listing photo. I'm Stanley Montfort, a NYC buyer's agent specializing in multifamily properties, and this guide walks you through everything I tell my clients before they make an offer.</p>
          <h2 style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 32, lineHeight: "1.22", letterSpacing: "-0.01em", color: "#0F1729", margin: "44px 0 0", textWrap: "pretty" }}>Why NYC buyers trust Stanley Montfort</h2>
          <p style={{ fontSize: 17, lineHeight: "1.85", color: "#3B4C5E", margin: "16px 0 0", textWrap: "pretty" }}>When you're making what is often a $750,000 to $1,000,000+ purchase that doubles as both your residence and your investment portfolio, you need an agent who understands both sides of that equation.</p>
          <ul style={{ margin: "16px 0 0", padding: 0, listStyle: "none", display: "flex", flexDirection: "column", gap: "12px" }}><li style={{ position: "relative", paddingLeft: "30px", fontSize: 17, lineHeight: "1.7", color: "#3B4C5E", textWrap: "pretty" }}><span style={{ position: "absolute", left: 0, top: 9, width: 9, height: 9, borderRadius: "50%", background: "#C98A2C" }}></span><strong style={{ fontWeight: "700", color: "#0F1729" }}>Specialized expertise</strong> in NYC two-family house transactions across all five boroughs</li><li style={{ position: "relative", paddingLeft: "30px", fontSize: 17, lineHeight: "1.7", color: "#3B4C5E", textWrap: "pretty" }}><span style={{ position: "absolute", left: 0, top: 9, width: 9, height: 9, borderRadius: "50%", background: "#C98A2C" }}></span><strong style={{ fontWeight: "700", color: "#0F1729" }}>Deep knowledge of NYC zoning laws</strong>, Certificate of Occupancy requirements, and building permit history</li><li style={{ position: "relative", paddingLeft: "30px", fontSize: 17, lineHeight: "1.7", color: "#3B4C5E", textWrap: "pretty" }}><span style={{ position: "absolute", left: 0, top: 9, width: 9, height: 9, borderRadius: "50%", background: "#C98A2C" }}></span><strong style={{ fontWeight: "700", color: "#0F1729" }}>Rapid property evaluations</strong> with thorough market analysis so you can move confidently</li><li style={{ position: "relative", paddingLeft: "30px", fontSize: 17, lineHeight: "1.7", color: "#3B4C5E", textWrap: "pretty" }}><span style={{ position: "absolute", left: 0, top: 9, width: 9, height: 9, borderRadius: "50%", background: "#C98A2C" }}></span><strong style={{ fontWeight: "700", color: "#0F1729" }}>Proven track record</strong> helping first-time buyers, owner-occupants, and investors from search through closing</li></ul>
          <div style={{ margin: "34px 0 0", borderRadius: "16px", overflow: "hidden", border: "1px solid #E0D9B8", boxShadow: "0 26px 54px rgba(17,59,95,0.14)" }}><img src="/redesign-assets/services/2-family-house-for-sale-nyc.webp" alt="2 family house for sale NYC" loading="lazy" style={{ display: "block", width: "100%", height: "auto" }} /></div>
          <h2 style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 32, lineHeight: "1.22", letterSpacing: "-0.01em", color: "#0F1729", margin: "44px 0 0", textWrap: "pretty" }}>What qualifies as a legal 2 family house in NYC</h2>
          <p style={{ fontSize: 17, lineHeight: "1.85", color: "#3B4C5E", margin: "16px 0 0", textWrap: "pretty" }}>Many buyers assume that if a property is listed as a two-family home, it must be legally configured that way. That assumption has cost people tens of thousands of dollars. A <a href="https://dos.ny.gov/legal-memorandum-lu05-definition-family-zoning-law-and-building-codes" style={{ color: "#113B5F", borderBottom: "1px solid #C98A2C" }} {...{ "style-hover": "color:#C98A2C" }}>legal two-family dwelling</a> contains no more than two units, each with independent living facilities. The listing description doesn't make it legal, the Certificate of Occupancy does.</p>
          <h3 style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 21, lineHeight: "1.3", letterSpacing: "-0.005em", color: "#113B5F", margin: "30px 0 0", textWrap: "pretty" }}>Certificate of Occupancy requirements</h3>
          <p style={{ fontSize: 17, lineHeight: "1.85", color: "#3B4C5E", margin: "16px 0 0", textWrap: "pretty" }}>A CO confirms a building complies with the NYC Building Code, zoning resolution, plumbing, fire safety, and electrical standards. Buildings constructed before 1938 may be exempt but can seek a Letter of No Objection. I always pull records from the DOB's BIS and DOB NOW portals to verify.</p>
          <h3 style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 21, lineHeight: "1.3", letterSpacing: "-0.005em", color: "#113B5F", margin: "30px 0 0", textWrap: "pretty" }}>Zoning compliance and unit configuration</h3>
          <p style={{ fontSize: 17, lineHeight: "1.85", color: "#3B4C5E", margin: "16px 0 0", textWrap: "pretty" }}>In districts such as R3A, R3X, R4A, and R4-1, two-family residences must follow specific layout rules, for example, at least <a href="https://zr.planning.nyc.gov/node/18174" style={{ color: "#113B5F", borderBottom: "1px solid #C98A2C" }} {...{ "style-hover": "color:#C98A2C" }}>75% of one unit must sit directly above or below the other</a>. Always verify the zoning district before falling in love with a property.</p>
          <h3 style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 21, lineHeight: "1.3", letterSpacing: "-0.005em", color: "#113B5F", margin: "30px 0 0", textWrap: "pretty" }}>Common disqualifiers</h3>
          <ul style={{ margin: "16px 0 0", padding: 0, listStyle: "none", display: "flex", flexDirection: "column", gap: "12px" }}><li style={{ position: "relative", paddingLeft: "30px", fontSize: 17, lineHeight: "1.7", color: "#3B4C5E", textWrap: "pretty" }}><span style={{ position: "absolute", left: 0, top: 9, width: 9, height: 9, borderRadius: "50%", background: "#C98A2C" }}></span>Basement or cellar units without proper permits, egress windows, or ceiling height</li><li style={{ position: "relative", paddingLeft: "30px", fontSize: 17, lineHeight: "1.7", color: "#3B4C5E", textWrap: "pretty" }}><span style={{ position: "absolute", left: 0, top: 9, width: 9, height: 9, borderRadius: "50%", background: "#C98A2C" }}></span>Kitchens or bathrooms added without building permits</li><li style={{ position: "relative", paddingLeft: "30px", fontSize: 17, lineHeight: "1.7", color: "#3B4C5E", textWrap: "pretty" }}><span style={{ position: "absolute", left: 0, top: 9, width: 9, height: 9, borderRadius: "50%", background: "#C98A2C" }}></span>Properties listed as two-family but with a CO for single-family use</li><li style={{ position: "relative", paddingLeft: "30px", fontSize: 17, lineHeight: "1.7", color: "#3B4C5E", textWrap: "pretty" }}><span style={{ position: "absolute", left: 0, top: 9, width: 9, height: 9, borderRadius: "50%", background: "#C98A2C" }}></span>Open DOB violations that must be resolved before sale or financing</li><li style={{ position: "relative", paddingLeft: "30px", fontSize: 17, lineHeight: "1.7", color: "#3B4C5E", textWrap: "pretty" }}><span style={{ position: "absolute", left: 0, top: 9, width: 9, height: 9, borderRadius: "50%", background: "#C98A2C" }}></span>Units that don't meet fire safety and egress requirements</li></ul>
          <h2 style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 32, lineHeight: "1.22", letterSpacing: "-0.01em", color: "#0F1729", margin: "44px 0 0", textWrap: "pretty" }}>Benefits of owning a 2 family property in NYC</h2>
          <h3 style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 21, lineHeight: "1.3", letterSpacing: "-0.005em", color: "#113B5F", margin: "30px 0 0", textWrap: "pretty" }}>Live in one unit while generating rental income</h3>
          <p style={{ fontSize: 17, lineHeight: "1.85", color: "#3B4C5E", margin: "16px 0 0", textWrap: "pretty" }}>You occupy one unit and rent the other, using that <a href="/nyc-first-time-home-buyer-mortages/" style={{ color: "#113B5F", borderBottom: "1px solid #C98A2C" }} {...{ "style-hover": "color:#C98A2C" }}>rental income to offset your mortgage</a>, taxes, and insurance. In Queens neighborhoods like Ozone Park and Richmond Hill, rents run roughly <strong style={{ fontWeight: "700", color: "#0F1729" }}>$2,000–$2,600/month</strong> per unit depending on size and condition.</p>
          <div style={{ margin: "34px 0 0", borderRadius: "16px", overflow: "hidden", border: "1px solid #E0D9B8", boxShadow: "0 26px 54px rgba(17,59,95,0.14)" }}><img src="/redesign-assets/services/2-family-investment.webp" alt="Investment and appreciation for family house" loading="lazy" style={{ display: "block", width: "100%", height: "auto" }} /></div>
          <h3 style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 21, lineHeight: "1.3", letterSpacing: "-0.005em", color: "#113B5F", margin: "30px 0 0", textWrap: "pretty" }}>Long-term investment and appreciation</h3>
          <p style={{ fontSize: 17, lineHeight: "1.85", color: "#3B4C5E", margin: "16px 0 0", textWrap: "pretty" }}>NYC real estate has historically appreciated over time, and two-family houses in emerging neighborhoods offer both current income and future value growth, you're building equity in two units rather than one.</p>
          <h3 style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 21, lineHeight: "1.3", letterSpacing: "-0.005em", color: "#113B5F", margin: "30px 0 0", textWrap: "pretty" }}>Tax advantages & equity building</h3>
          <p style={{ fontSize: 17, lineHeight: "1.85", color: "#3B4C5E", margin: "16px 0 0", textWrap: "pretty" }}>Owners can deduct mortgage interest, property taxes, insurance, repairs, and depreciation on the rental portion. Every payment builds equity across the whole property while your tenant's rent helps cover it.</p>
          <h2 style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 32, lineHeight: "1.22", letterSpacing: "-0.01em", color: "#0F1729", margin: "44px 0 0", textWrap: "pretty" }}>The 2 family house buying process</h2>
          <h3 style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 21, lineHeight: "1.3", letterSpacing: "-0.005em", color: "#113B5F", margin: "30px 0 0", textWrap: "pretty" }}>Step 1, Consultation and property search</h3>
          <p style={{ fontSize: 17, lineHeight: "1.85", color: "#3B4C5E", margin: "16px 0 0", textWrap: "pretty" }}>Before looking at a single listing, I sit down with every client to understand their goals: owner-occupancy vs. pure investment, budget, and target neighborhoods. Those answers shape financing strategy and search criteria, and we get pre-approved for multifamily financing up front.</p>
          <h3 style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 21, lineHeight: "1.3", letterSpacing: "-0.005em", color: "#113B5F", margin: "30px 0 0", textWrap: "pretty" }}>Step 2, Property evaluation and due diligence</h3>
          <ul style={{ margin: "16px 0 0", padding: 0, listStyle: "none", display: "flex", flexDirection: "column", gap: "12px" }}><li style={{ position: "relative", paddingLeft: "30px", fontSize: 17, lineHeight: "1.7", color: "#3B4C5E", textWrap: "pretty" }}><span style={{ position: "absolute", left: 0, top: 9, width: 9, height: 9, borderRadius: "50%", background: "#C98A2C" }}></span><strong style={{ fontWeight: "700", color: "#0F1729" }}>Comprehensive inspection</strong>, structure, roof, plumbing age, electrical capacity, HVAC, and foundation</li><li style={{ position: "relative", paddingLeft: "30px", fontSize: 17, lineHeight: "1.7", color: "#3B4C5E", textWrap: "pretty" }}><span style={{ position: "absolute", left: 0, top: 9, width: 9, height: 9, borderRadius: "50%", background: "#C98A2C" }}></span><strong style={{ fontWeight: "700", color: "#0F1729" }}>Rental income analysis</strong>, comparable rents, current leases, and realistic vacancy</li><li style={{ position: "relative", paddingLeft: "30px", fontSize: 17, lineHeight: "1.7", color: "#3B4C5E", textWrap: "pretty" }}><span style={{ position: "absolute", left: 0, top: 9, width: 9, height: 9, borderRadius: "50%", background: "#C98A2C" }}></span><strong style={{ fontWeight: "700", color: "#0F1729" }}>Deferred maintenance assessment</strong>, major items like roof, plumbing, or panel replacement can run $15,000–$50,000+</li><li style={{ position: "relative", paddingLeft: "30px", fontSize: 17, lineHeight: "1.7", color: "#3B4C5E", textWrap: "pretty" }}><span style={{ position: "absolute", left: 0, top: 9, width: 9, height: 9, borderRadius: "50%", background: "#C98A2C" }}></span><strong style={{ fontWeight: "700", color: "#0F1729" }}>Operating expense verification</strong>, taxes (~0.88%–1.2% of assessed value), insurance, and utility arrangements</li></ul>
          <h3 style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 21, lineHeight: "1.3", letterSpacing: "-0.005em", color: "#113B5F", margin: "30px 0 0", textWrap: "pretty" }}>Step 3, Offer strategy and negotiation</h3>
          <ul style={{ margin: "16px 0 0", padding: 0, listStyle: "none", display: "flex", flexDirection: "column", gap: "12px" }}><li style={{ position: "relative", paddingLeft: "30px", fontSize: 17, lineHeight: "1.7", color: "#3B4C5E", textWrap: "pretty" }}><span style={{ position: "absolute", left: 0, top: 9, width: 9, height: 9, borderRadius: "50%", background: "#C98A2C" }}></span><strong style={{ fontWeight: "700", color: "#0F1729" }}>Cap rate calculation</strong>, Queens two-family cap rates generally range 5–8% before vacancy and repairs</li><li style={{ position: "relative", paddingLeft: "30px", fontSize: 17, lineHeight: "1.7", color: "#3B4C5E", textWrap: "pretty" }}><span style={{ position: "absolute", left: 0, top: 9, width: 9, height: 9, borderRadius: "50%", background: "#C98A2C" }}></span><strong style={{ fontWeight: "700", color: "#0F1729" }}>Price per unit and per square foot</strong> comparisons against local inventory</li><li style={{ position: "relative", paddingLeft: "30px", fontSize: 17, lineHeight: "1.7", color: "#3B4C5E", textWrap: "pretty" }}><span style={{ position: "absolute", left: 0, top: 9, width: 9, height: 9, borderRadius: "50%", background: "#C98A2C" }}></span><strong style={{ fontWeight: "700", color: "#0F1729" }}>Repair credits, closing contributions, and contingency terms</strong> that protect your investment</li></ul>
          <h3 style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 21, lineHeight: "1.3", letterSpacing: "-0.005em", color: "#113B5F", margin: "30px 0 0", textWrap: "pretty" }}>Step 4, Contract to closing</h3>
          <p style={{ fontSize: 17, lineHeight: "1.85", color: "#3B4C5E", margin: "16px 0 0", textWrap: "pretty" }}>Once under contract, I coordinate attorney review, final inspections, lender appraisal and title, and closing preparation, catching issues before they become problems.</p>
          <h2 style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 32, lineHeight: "1.22", letterSpacing: "-0.01em", color: "#0F1729", margin: "44px 0 0", textWrap: "pretty" }}>Financing considerations for 2 family houses</h2>
          <h3 style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 21, lineHeight: "1.3", letterSpacing: "-0.005em", color: "#113B5F", margin: "30px 0 0", textWrap: "pretty" }}>Owner-occupied financing</h3>
          <ul style={{ margin: "16px 0 0", padding: 0, listStyle: "none", display: "flex", flexDirection: "column", gap: "12px" }}><li style={{ position: "relative", paddingLeft: "30px", fontSize: 17, lineHeight: "1.7", color: "#3B4C5E", textWrap: "pretty" }}><span style={{ position: "absolute", left: 0, top: 9, width: 9, height: 9, borderRadius: "50%", background: "#C98A2C" }}></span><strong style={{ fontWeight: "700", color: "#0F1729" }}>FHA 203(b)</strong>, as little as 3.5% down with a 580+ credit score for a two-unit owner-occupied property</li><li style={{ position: "relative", paddingLeft: "30px", fontSize: 17, lineHeight: "1.7", color: "#3B4C5E", textWrap: "pretty" }}><span style={{ position: "absolute", left: 0, top: 9, width: 9, height: 9, borderRadius: "50%", background: "#C98A2C" }}></span><strong style={{ fontWeight: "700", color: "#0F1729" }}>SONYMA Low Interest Rate Program</strong>, competitive fixed-rate 30-year mortgages up to 97% LTV for 1–4 family homes</li><li style={{ position: "relative", paddingLeft: "30px", fontSize: 17, lineHeight: "1.7", color: "#3B4C5E", textWrap: "pretty" }}><span style={{ position: "absolute", left: 0, top: 9, width: 9, height: 9, borderRadius: "50%", background: "#C98A2C" }}></span><strong style={{ fontWeight: "700", color: "#0F1729" }}>NYC HomeFirst</strong>, up to $100,000 in forgivable loans toward down payment or closing costs for eligible first-time buyers</li></ul>
          <div style={{ margin: "34px 0 0", borderRadius: "16px", overflow: "hidden", border: "1px solid #E0D9B8", boxShadow: "0 26px 54px rgba(17,59,95,0.14)" }}><img src="/redesign-assets/services/mortgage.webp" alt="Mortgage calculator" loading="lazy" style={{ display: "block", width: "100%", height: "auto" }} /></div>
          <h3 style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 21, lineHeight: "1.3", letterSpacing: "-0.005em", color: "#113B5F", margin: "30px 0 0", textWrap: "pretty" }}>Investment property financing</h3>
          <p style={{ fontSize: 17, lineHeight: "1.85", color: "#3B4C5E", margin: "16px 0 0", textWrap: "pretty" }}>Conventional loans for non-owner-occupied two-family properties typically require <strong style={{ fontWeight: "700", color: "#0F1729" }}>15–25% down</strong> with higher rates and reserves. On an $850,000 purchase that's roughly $127,500–$212,500 down versus about $29,750 with FHA owner-occupied financing.</p>
          <h2 style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 32, lineHeight: "1.22", letterSpacing: "-0.01em", color: "#0F1729", margin: "44px 0 0", textWrap: "pretty" }}>NYC neighborhoods we serve</h2>
          <p style={{ fontSize: 17, lineHeight: "1.85", color: "#3B4C5E", margin: "16px 0 0", textWrap: "pretty" }}><strong style={{ fontWeight: "700", color: "#0F1729" }}>Brooklyn</strong>, Bed-Stuy, Crown Heights, Sunset Park, Bay Ridge, East Flatbush, and Canarsie. <strong style={{ fontWeight: "700", color: "#0F1729" }}>Queens</strong>, the largest two-family inventory: Ozone Park, Richmond Hill, Jackson Heights, Astoria, Elmhurst, and LIC. <strong style={{ fontWeight: "700", color: "#0F1729" }}>Bronx</strong>, Fordham, University Heights, Tremont, Morris Park, and Throggs Neck. <strong style={{ fontWeight: "700", color: "#0F1729" }}>Manhattan</strong> and <strong style={{ fontWeight: "700", color: "#0F1729" }}>Staten Island</strong> round out the search with select opportunities.</p>
          <h2 style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 32, lineHeight: "1.22", letterSpacing: "-0.01em", color: "#0F1729", margin: "44px 0 0", textWrap: "pretty" }}>Common buyer mistakes to avoid</h2>
          <ul style={{ margin: "16px 0 0", padding: 0, listStyle: "none", display: "flex", flexDirection: "column", gap: "12px" }}><li style={{ position: "relative", paddingLeft: "30px", fontSize: 17, lineHeight: "1.7", color: "#3B4C5E", textWrap: "pretty" }}><span style={{ position: "absolute", left: 0, top: 9, width: 9, height: 9, borderRadius: "50%", background: "#C98A2C" }}></span><strong style={{ fontWeight: "700", color: "#0F1729" }}>Assuming all 2-family houses are legally configured</strong>, always verify status through DOB records</li><li style={{ position: "relative", paddingLeft: "30px", fontSize: 17, lineHeight: "1.7", color: "#3B4C5E", textWrap: "pretty" }}><span style={{ position: "absolute", left: 0, top: 9, width: 9, height: 9, borderRadius: "50%", background: "#C98A2C" }}></span><strong style={{ fontWeight: "700", color: "#0F1729" }}>Overestimating rental income</strong> without real comparable data</li><li style={{ position: "relative", paddingLeft: "30px", fontSize: 17, lineHeight: "1.7", color: "#3B4C5E", textWrap: "pretty" }}><span style={{ position: "absolute", left: 0, top: 9, width: 9, height: 9, borderRadius: "50%", background: "#C98A2C" }}></span><strong style={{ fontWeight: "700", color: "#0F1729" }}>Underestimating maintenance</strong>, budget 1–3% of property value annually</li><li style={{ position: "relative", paddingLeft: "30px", fontSize: 17, lineHeight: "1.7", color: "#3B4C5E", textWrap: "pretty" }}><span style={{ position: "absolute", left: 0, top: 9, width: 9, height: 9, borderRadius: "50%", background: "#C98A2C" }}></span><strong style={{ fontWeight: "700", color: "#0F1729" }}>Failing to account for vacancy and turnover</strong> costs</li><li style={{ position: "relative", paddingLeft: "30px", fontSize: 17, lineHeight: "1.7", color: "#3B4C5E", textWrap: "pretty" }}><span style={{ position: "absolute", left: 0, top: 9, width: 9, height: 9, borderRadius: "50%", background: "#C98A2C" }}></span><strong style={{ fontWeight: "700", color: "#0F1729" }}>Not reviewing building permits and alteration history</strong>, unpermitted work can make a property unfinanceable</li></ul>
          <h2 style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 32, lineHeight: "1.22", letterSpacing: "-0.01em", color: "#0F1729", margin: "44px 0 0", textWrap: "pretty" }}>Frequently asked questions</h2>
          <h3 style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 21, lineHeight: "1.3", letterSpacing: "-0.005em", color: "#113B5F", margin: "30px 0 0", textWrap: "pretty" }}>How much rental income can a two-family house generate?</h3>
          <p style={{ fontSize: 17, lineHeight: "1.85", color: "#3B4C5E", margin: "16px 0 0", textWrap: "pretty" }}>It depends on neighborhood, unit size, condition, and demand. In Queens, units currently rent for roughly $2,000–$2,600/month. I provide every client a detailed analysis using current market data, not best-case projections.</p>
          <h3 style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 21, lineHeight: "1.3", letterSpacing: "-0.005em", color: "#113B5F", margin: "30px 0 0", textWrap: "pretty" }}>Can I live in one unit while renting the other?</h3>
          <p style={{ fontSize: 17, lineHeight: "1.85", color: "#3B4C5E", margin: "16px 0 0", textWrap: "pretty" }}>Yes, this is the most common strategy. FHA and SONYMA financing require owner-occupancy, so you live in one unit as your primary residence and rent the second, subject to any existing leases.</p>
          <h3 style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 21, lineHeight: "1.3", letterSpacing: "-0.005em", color: "#113B5F", margin: "30px 0 0", textWrap: "pretty" }}>How do I verify a property is legally a two-family house?</h3>
          <p style={{ fontSize: 17, lineHeight: "1.85", color: "#3B4C5E", margin: "16px 0 0", textWrap: "pretty" }}>Request the Certificate of Occupancy through the NYC DOB or BIS portal, cross-reference the physical layout during inspection, and check for open violations and permit history. This verification is standard in every evaluation I conduct.</p>
          <h3 style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 21, lineHeight: "1.3", letterSpacing: "-0.005em", color: "#113B5F", margin: "30px 0 0", textWrap: "pretty" }}>What should I evaluate during inspection?</h3>
          <ul style={{ margin: "16px 0 0", padding: 0, listStyle: "none", display: "flex", flexDirection: "column", gap: "12px" }}><li style={{ position: "relative", paddingLeft: "30px", fontSize: 17, lineHeight: "1.7", color: "#3B4C5E", textWrap: "pretty" }}><span style={{ position: "absolute", left: 0, top: 9, width: 9, height: 9, borderRadius: "50%", background: "#C98A2C" }}></span><strong style={{ fontWeight: "700", color: "#0F1729" }}>Separate utility meters</strong> for electric, gas, and water</li><li style={{ position: "relative", paddingLeft: "30px", fontSize: 17, lineHeight: "1.7", color: "#3B4C5E", textWrap: "pretty" }}><span style={{ position: "absolute", left: 0, top: 9, width: 9, height: 9, borderRadius: "50%", background: "#C98A2C" }}></span><strong style={{ fontWeight: "700", color: "#0F1729" }}>Legal unit configurations</strong>, each with its own kitchen, bath, sleeping area, and egress</li><li style={{ position: "relative", paddingLeft: "30px", fontSize: 17, lineHeight: "1.7", color: "#3B4C5E", textWrap: "pretty" }}><span style={{ position: "absolute", left: 0, top: 9, width: 9, height: 9, borderRadius: "50%", background: "#C98A2C" }}></span><strong style={{ fontWeight: "700", color: "#0F1729" }}>Structural systems</strong>, foundation, roof age, plumbing, and electrical capacity</li><li style={{ position: "relative", paddingLeft: "30px", fontSize: 17, lineHeight: "1.7", color: "#3B4C5E", textWrap: "pretty" }}><span style={{ position: "absolute", left: 0, top: 9, width: 9, height: 9, borderRadius: "50%", background: "#C98A2C" }}></span><strong style={{ fontWeight: "700", color: "#0F1729" }}>Signs of unpermitted work</strong> and <strong style={{ fontWeight: "700", color: "#0F1729" }}>fire safety compliance</strong></li></ul>
          <h2 style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 32, lineHeight: "1.22", letterSpacing: "-0.01em", color: "#0F1729", margin: "44px 0 0", textWrap: "pretty" }}>Start your 2 family house search today</h2>
          <p style={{ fontSize: 17, lineHeight: "1.85", color: "#3B4C5E", margin: "16px 0 0", textWrap: "pretty" }}>Finding the right two-family house in NYC takes an experienced buyer's agent who understands legal configuration, realistic investment analysis, and neighborhood rental demand. I guide every client from initial consultation through closing so you know exactly what you're buying, what it costs to operate, and what it can realistically earn.</p>
    
          <div style={{ margin: "52px 0 0", background: "#113B5F", borderRadius: "16px", padding: "44px 48px", textAlign: "center" }}>
           <div style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 26, color: "#F9F6E6", textWrap: "pretty" }}>Ready to buy a two-family home the smart way?</div>
           <p style={{ fontSize: 16, lineHeight: "1.7", color: "rgba(249,246,230,0.85)", margin: "14px auto 0", maxWidth: 560 }}>Twenty minutes on the phone is all it takes to map out your next move.</p>
           <div style={{ display: "flex", flexWrap: "wrap", gap: "14px", justifyContent: "center", marginTop: 28 }}>
            <a href="tel:646-970-1078" style={{ display: "inline-flex", alignItems: "center", justifyContent: "center", background: "#C98A2C", color: "#0F1729", fontSize: 14, fontWeight: "800", letterSpacing: "0.06em", textTransform: "uppercase", borderRadius: "100px", padding: "17px 32px", minHeight: 54 }} {...{ "style-hover": "background:#F9F6E6; color:#113B5F" }}>Call 1-646-970-1078</a>
            <a href="https://calendly.com/montfort" style={{ display: "inline-flex", alignItems: "center", justifyContent: "center", border: "2px solid rgba(240,217,168,0.55)", color: "#F9F6E6", fontSize: 14, fontWeight: "800", letterSpacing: "0.06em", textTransform: "uppercase", borderRadius: "100px", padding: "15px 30px", minHeight: 54 }} {...{ "style-hover": "background:#F9F6E6; color:#113B5F; border-color:#F9F6E6" }}>Schedule a Consultation</a>
           </div>
           <div style={{ fontSize: 14, color: "rgba(249,246,230,0.7)", marginTop: 24 }}>8 West 126th Street, New York, NY 10027 · <a href="mailto:sm@montfortre.com" style={{ color: "#C98A2C" }}>sm@montfortre.com</a></div>
          </div>
         </div>
        </div>
       </section>
      <ResourcesSection />
      <ContactSection />
    </>
  );
}
