import ContactSection from "../shared/ContactSection";

export default function BrownstoneGuideContent() {
  return (
    <>
      <section data-screen-label="Article hero" style={{ position: "relative", background: "#F5EECB", borderBottom: "1px solid #E0D9B8", overflow: "hidden", padding: "80px 64px 90px" }}>
        <div style={{ position: "absolute", top: -150, right: -160, width: 560, height: 560, borderRadius: "50%", border: "1px solid rgba(201,138,44,0.2)" }}></div>
        <div style={{ position: "relative", zIndex: "2", maxWidth: 1440, margin: "0 auto", display: "grid", gridTemplateColumns: "1.02fr 0.98fr", gap: "72px", alignItems: "center" }}>
         <div data-reveal="">
          <div style={{ display: "inline-flex", alignItems: "center", gap: "10px", fontSize: 11, fontWeight: "700", letterSpacing: "0.16em", textTransform: "uppercase", color: "#8A7B4E" }}><a href="/blog/" style={{ color: "#8A7B4E" }}>Resources</a> <span style={{ opacity: ".5" }}>/</span> <span style={{ color: "#C98A2C" }}>Buyer Guide</span></div>
          <h1 style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 52, lineHeight: "1.08", letterSpacing: "-0.02em", color: "#0F1729", margin: "18px 0 0", textWrap: "pretty" }}>Brownstone Buying Guide for Buyers</h1>
          <p style={{ fontSize: 19, lineHeight: "1.7", color: "#3B4C5E", margin: "20px 0 0", maxWidth: 540, textWrap: "pretty" }}>Everything you should expect when you buy and own a brownstone in New York City, from long-term commitment to repairs, taxes, and maintenance.</p>
          <div style={{ display: "flex", alignItems: "center", gap: "12px", marginTop: 24, fontSize: 14, color: "#52677A" }}>By <a href="/stanley-montfort/" style={{ color: "#113B5F", borderBottom: "1px solid #C98A2C" }} {...{ "style-hover": "color:#C98A2C" }}>Stanley Montfort</a> <span style={{ color: "#C98A2C" }}>·</span> NYC Buyer's Agent</div>
          <div style={{ display: "flex", flexWrap: "wrap", gap: "14px", marginTop: 32 }}>
           <a href="https://calendly.com/montfort" style={{ display: "inline-flex", alignItems: "center", justifyContent: "center", background: "#113B5F", color: "#F9F6E6", fontSize: 15, fontWeight: "800", letterSpacing: "0.05em", textTransform: "uppercase", borderRadius: "100px", padding: "18px 34px", minHeight: 56 }} {...{ "style-hover": "background:#C98A2C; color:#0F1729" }}>Book Now</a>
           <a href="tel:646-970-1078" style={{ display: "inline-flex", alignItems: "center", justifyContent: "center", border: "2px solid #113B5F", color: "#113B5F", fontSize: 15, fontWeight: "800", letterSpacing: "0.03em", borderRadius: "100px", padding: "16px 30px", minHeight: 56 }} {...{ "style-hover": "background:#113B5F; color:#F9F6E6" }}>(646) 970-1078</a>
          </div>
         </div>
         <div data-reveal="" style={{ position: "relative" }}>
          <div style={{ position: "absolute", top: -18, left: -18, width: 16, height: 16, borderRadius: "50%", background: "#C98A2C" }}></div>
          <div style={{ position: "relative", borderRadius: "16px", overflow: "hidden", aspectRatio: "3/2", background: "#E0D9B8", border: "6px solid #FFFFFF", boxShadow: "0 40px 90px rgba(17,59,95,0.28)" }}>
           <img src="/redesign-assets/blog/brownstone-buying-guide.webp" alt="Brownstone Buying Guide" style={{ position: "absolute", inset: 0, width: "100%", height: "100%", objectFit: "cover", display: "block" }} />
          </div>
         </div>
        </div>
       </section>
       <section data-screen-label="Article" style={{ background: "#fff", padding: "100px 64px 100px", borderBottom: "1px solid #E0D9B8" }}>
        <div style={{ maxWidth: 1440, margin: "0 auto", display: "grid", gridTemplateColumns: "240px minmax(0,1fr)", gap: "56px", alignItems: "start" }}>
         <aside style={{ position: "sticky", top: 110, alignSelf: "start" }}>
          <div style={{ fontSize: "11.5px", fontWeight: "700", letterSpacing: "0.18em", textTransform: "uppercase", color: "#C98A2C", marginBottom: 18 }}>On this page</div>
          <nav style={{ display: "flex", flexDirection: "column", gap: "2px", borderLeft: "1px solid #E0D9B8" }}>
           <a href="#brownstones-long-term" style={{ padding: "9px 16px", fontSize: 14, lineHeight: "1.4", color: "#3B4C5E", borderLeft: "2px solid transparent", marginLeft: "-1px", textWrap: "pretty" }} {...{ "style-hover": "color:#C98A2C; border-left-color:#C98A2C" }}>Long-term commitments</a>
           <a href="#repairs" style={{ padding: "9px 16px", fontSize: 14, lineHeight: "1.4", color: "#3B4C5E", borderLeft: "2px solid transparent", marginLeft: "-1px", textWrap: "pretty" }} {...{ "style-hover": "color:#C98A2C; border-left-color:#C98A2C" }}>Repairs</a>
           <a href="#taxes" style={{ padding: "9px 16px", fontSize: 14, lineHeight: "1.4", color: "#3B4C5E", borderLeft: "2px solid transparent", marginLeft: "-1px", textWrap: "pretty" }} {...{ "style-hover": "color:#C98A2C; border-left-color:#C98A2C" }}>Taxes</a>
           <a href="#roof-repairs" style={{ padding: "9px 16px", fontSize: 14, lineHeight: "1.4", color: "#3B4C5E", borderLeft: "2px solid transparent", marginLeft: "-1px", textWrap: "pretty" }} {...{ "style-hover": "color:#C98A2C; border-left-color:#C98A2C" }}>Roof repairs</a>
           <a href="#facade" style={{ padding: "9px 16px", fontSize: 14, lineHeight: "1.4", color: "#3B4C5E", borderLeft: "2px solid transparent", marginLeft: "-1px", textWrap: "pretty" }} {...{ "style-hover": "color:#C98A2C; border-left-color:#C98A2C" }}>Facade</a>
           <a href="#windows" style={{ padding: "9px 16px", fontSize: 14, lineHeight: "1.4", color: "#3B4C5E", borderLeft: "2px solid transparent", marginLeft: "-1px", textWrap: "pretty" }} {...{ "style-hover": "color:#C98A2C; border-left-color:#C98A2C" }}>Windows</a>
           <a href="#fireplaces" style={{ padding: "9px 16px", fontSize: 14, lineHeight: "1.4", color: "#3B4C5E", borderLeft: "2px solid transparent", marginLeft: "-1px", textWrap: "pretty" }} {...{ "style-hover": "color:#C98A2C; border-left-color:#C98A2C" }}>Fireplaces</a>
           <a href="#air-conditioning" style={{ padding: "9px 16px", fontSize: 14, lineHeight: "1.4", color: "#3B4C5E", borderLeft: "2px solid transparent", marginLeft: "-1px", textWrap: "pretty" }} {...{ "style-hover": "color:#C98A2C; border-left-color:#C98A2C" }}>Air conditioning</a>
           <a href="#stairs" style={{ padding: "9px 16px", fontSize: 14, lineHeight: "1.4", color: "#3B4C5E", borderLeft: "2px solid transparent", marginLeft: "-1px", textWrap: "pretty" }} {...{ "style-hover": "color:#C98A2C; border-left-color:#C98A2C" }}>Stairs</a>
           <a href="#backyard-space" style={{ padding: "9px 16px", fontSize: 14, lineHeight: "1.4", color: "#3B4C5E", borderLeft: "2px solid transparent", marginLeft: "-1px", textWrap: "pretty" }} {...{ "style-hover": "color:#C98A2C; border-left-color:#C98A2C" }}>Backyard space</a>
           <a href="#faqs" style={{ padding: "9px 16px", fontSize: 14, lineHeight: "1.4", color: "#3B4C5E", borderLeft: "2px solid transparent", marginLeft: "-1px", textWrap: "pretty" }} {...{ "style-hover": "color:#C98A2C; border-left-color:#C98A2C" }}>FAQs</a>
          </nav>
         </aside>
         <div data-reveal="" style={{ maxWidth: "100%" }}>
          <div style={{ display: "flex", alignItems: "center", gap: "14px", marginBottom: 8 }}><span style={{ width: 34, height: 1, background: "#C98A2C", display: "block" }}></span><span style={{ fontSize: "11.5px", fontWeight: "600", letterSpacing: "0.18em", textTransform: "uppercase", color: "#3B4C5E" }}>The guide</span></div>
    
          <p style={{ fontSize: 17, lineHeight: "1.85", color: "#3B4C5E", margin: "16px 0 0", textWrap: "pretty" }}>For a lot of residents of New York, owning a brownstone is a dream come true. <a href="/brownstones-in-new-york-city/" style={{ color: "#113B5F", borderBottom: "1px solid #C98A2C" }} {...{ "style-hover": "color:#C98A2C" }}>Brownstones</a> have a lot of space, a rarity in NYC, and most have extra rooms for friends and in-laws when they visit the Big Apple. For the most part, owning a brownstone is amazing; until you commit to a mortgage and find out your dream brownstone comes with more responsibility than you expected. Owning a brownstone in New York City is a privilege, but it's a major commitment and a long-term investment that requires patience.</p>
          <p style={{ fontSize: 17, lineHeight: "1.85", color: "#3B4C5E", margin: "16px 0 0", textWrap: "pretty" }}>If you believe purchasing a brownstone in New York City is for you, read on for what to expect when you buy and own one.</p>
          <h2 id="brownstones-long-term" style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 30, lineHeight: "1.24", letterSpacing: "-0.01em", color: "#0F1729", margin: "44px 0 0", textWrap: "pretty", scrollMarginTop: "110px" }}>Brownstones are long-term commitments</h2>
          <p style={{ fontSize: 17, lineHeight: "1.85", color: "#3B4C5E", margin: "16px 0 0", textWrap: "pretty" }}>Purchasing any type of property in NYC is a huge accomplishment, especially a brownstone, and especially as a first-time homebuyer. A brownstone is more than a short-term financial play; it's a long-term investment that requires careful budgeting and lifestyle changes to reap the benefits.</p>
          <p style={{ fontSize: 17, lineHeight: "1.85", color: "#3B4C5E", margin: "16px 0 0", textWrap: "pretty" }}>A brownstone isn't really a starter home, they have generous space and require specialized maintenance, and they're commonly located in pricier neighborhoods like the Upper West Side and Brooklyn Heights. Most single-family brownstones in Manhattan go for over $2 million. If you're not planning to stay more than 10 years, it may be smarter financially to buy a condo or co-op, unless you're purchasing a 3–4 unit brownstone.</p>
          <h2 id="repairs" style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 30, lineHeight: "1.24", letterSpacing: "-0.01em", color: "#0F1729", margin: "44px 0 0", textWrap: "pretty", scrollMarginTop: "110px" }}>Repairs</h2>
          <p style={{ fontSize: 17, lineHeight: "1.85", color: "#3B4C5E", margin: "16px 0 0", textWrap: "pretty" }}>One of the primary benefits of owning a brownstone is autonomy and privacy, you don't answer to anyone. The downside: when things break, there's no Super to call. You're responsible for every issue, from a leaking roof to a lockout to cable that suddenly stops working. Be prepared to handle these yourself, and keep a vetted team of contractors and handymen on speed dial.</p>
          <h2 id="taxes" style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 30, lineHeight: "1.24", letterSpacing: "-0.01em", color: "#0F1729", margin: "44px 0 0", textWrap: "pretty", scrollMarginTop: "110px" }}>Taxes</h2>
          <p style={{ fontSize: 17, lineHeight: "1.85", color: "#3B4C5E", margin: "16px 0 0", textWrap: "pretty" }}>A major benefit of owning a brownstone is that they're typically taxed less than apartments. Single-family homes, including townhouses and brownstones, or a building with fewer than three units, are assessed at a much lower rate than buildings with more than three units. Additionally, with a brownstone you don't pay monthly maintenance fees, association fees, or common charges.</p>
          <h2 id="roof-repairs" style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 30, lineHeight: "1.24", letterSpacing: "-0.01em", color: "#0F1729", margin: "44px 0 0", textWrap: "pretty", scrollMarginTop: "110px" }}>Roof repairs</h2>
          <p style={{ fontSize: 17, lineHeight: "1.85", color: "#3B4C5E", margin: "16px 0 0", textWrap: "pretty" }}>As the owner, you're responsible for maintaining the roof over your head, literally. Before you buy, understand the roof's repair history and maintenance schedule; your home inspector should flag any looming issues. Two common problems are separation of the roof and water intrusion. Set up a semiannual maintenance schedule and have the roof checked by a professional after hard winters or heavy snow.</p>
          <h2 id="facade" style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 30, lineHeight: "1.24", letterSpacing: "-0.01em", color: "#0F1729", margin: "44px 0 0", textWrap: "pretty", scrollMarginTop: "110px" }}>Facade</h2>
          <p style={{ fontSize: 17, lineHeight: "1.85", color: "#3B4C5E", margin: "16px 0 0", textWrap: "pretty" }}>Brownstone is a fairly soft material that erodes and decays over time, so owners must undertake extensive facade renovations to maintain appearance and structural integrity. A full facade repair can cost up to $100,000 for larger projects. The Landmarks Preservation Commission has stringent guidelines, hire a contractor familiar with LPC regulations to ensure you follow applicable NYC laws.</p>
          <h2 id="windows" style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 30, lineHeight: "1.24", letterSpacing: "-0.01em", color: "#0F1729", margin: "44px 0 0", textWrap: "pretty", scrollMarginTop: "110px" }}>Windows</h2>
          <p style={{ fontSize: 17, lineHeight: "1.85", color: "#3B4C5E", margin: "16px 0 0", textWrap: "pretty" }}>Windows in historic brownstones differ from those in other homes. They're beautiful but require meticulous care to maintain their historical appearance, hire a contractor who specializes in 19th-century windows and historic brownstones.</p>
          <h2 id="fireplaces" style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 30, lineHeight: "1.24", letterSpacing: "-0.01em", color: "#0F1729", margin: "44px 0 0", textWrap: "pretty", scrollMarginTop: "110px" }}>Fireplaces</h2>
          <p style={{ fontSize: 17, lineHeight: "1.85", color: "#3B4C5E", margin: "16px 0 0", textWrap: "pretty" }}>Fireplaces, particularly with wooden mantels, are a quintessential brownstone feature. If you own an entire building, chances are you'll have multiple. The mantels are delicate and susceptible to damage, so be prepared for frequent dusting and polishing. In NYC most fireplaces are decorative rather than functional; if you want a renovation, plan it into your overall project from the start to avoid extra cost later.</p>
          <h2 id="air-conditioning" style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 30, lineHeight: "1.24", letterSpacing: "-0.01em", color: "#0F1729", margin: "44px 0 0", textWrap: "pretty", scrollMarginTop: "110px" }}>Air conditioning</h2>
          <p style={{ fontSize: 17, lineHeight: "1.85", color: "#3B4C5E", margin: "16px 0 0", textWrap: "pretty" }}>Most brownstones don't have central air unless recently renovated. Your options are central AC, window units, or split AC systems. Many owners opt for HVAC during a full renovation; others choose less-invasive split systems that mount on walls and let you control each room's temperature independently.</p>
          <h2 id="stairs" style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 30, lineHeight: "1.24", letterSpacing: "-0.01em", color: "#0F1729", margin: "44px 0 0", textWrap: "pretty", scrollMarginTop: "110px" }}>Stairs</h2>
          <p style={{ fontSize: 17, lineHeight: "1.85", color: "#3B4C5E", margin: "16px 0 0", textWrap: "pretty" }}>A brownstone's multiple floors are a great feature, and multiple flights of stairs. Movers will thank you less, and stairs can become an issue as you near retirement. If that's a concern, consider a brownstone with an elevator.</p>
          <h2 id="backyard-space" style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 30, lineHeight: "1.24", letterSpacing: "-0.01em", color: "#0F1729", margin: "44px 0 0", textWrap: "pretty", scrollMarginTop: "110px" }}>Backyard space</h2>
          <p style={{ fontSize: 17, lineHeight: "1.85", color: "#3B4C5E", margin: "16px 0 0", textWrap: "pretty" }}>Owning a brownstone means enjoying a backyard garden or patio in the middle of NYC. Keep in mind plants, a grill, outdoor furniture, and accessories add up, and you're responsible for any trees in your yard, including regular trimming so they don't threaten your property or a neighbor's.</p>
          <p style={{ fontSize: 17, lineHeight: "1.85", color: "#3B4C5E", margin: "16px 0 0", textWrap: "pretty" }}>Overall, living in a brownstone is a unique experience, and there are great services for everything above that might have given you pause.</p>

          <h2 id="faqs" style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 30, lineHeight: "1.24", letterSpacing: "-0.01em", color: "#0F1729", margin: "52px 0 0", textWrap: "pretty", scrollMarginTop: "110px" }}>Frequently asked questions</h2>
          <div style={{ display: "flex", flexDirection: "column", gap: "12px", marginTop: 24 }}>
           <details style={{ background: "#F9F6E6", border: "1px solid #E0D9B8", borderRadius: "16px", padding: "4px 26px" }} open>
            <summary style={{ listStyle: "none", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "space-between", gap: "20px", padding: "20px 0", fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 19, color: "#0F1729" }}>How much does a brownstone cost in NYC?<span style={{ flex: "0 0 auto", color: "#C98A2C", fontSize: 24, lineHeight: "1" }}>+</span></summary>
            <p style={{ fontSize: 16, lineHeight: "1.8", color: "#3B4C5E", margin: "0 0 22px", textWrap: "pretty" }}>Most single-family brownstones in Manhattan trade for over $2 million, with prices varying widely by neighborhood and condition. Multi-unit brownstones and those needing renovation can fall below that, while turnkey homes in prime areas command a premium.</p>
           </details>
           <details style={{ background: "#F9F6E6", border: "1px solid #E0D9B8", borderRadius: "16px", padding: "4px 26px" }}>
            <summary style={{ listStyle: "none", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "space-between", gap: "20px", padding: "20px 0", fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 19, color: "#0F1729" }}>Are brownstones a good investment?<span style={{ flex: "0 0 auto", color: "#C98A2C", fontSize: 24, lineHeight: "1" }}>+</span></summary>
            <p style={{ fontSize: 16, lineHeight: "1.8", color: "#3B4C5E", margin: "0 0 22px", textWrap: "pretty" }}>They can be an excellent long-term investment, especially if you plan to hold for 10 years or more. Brownstones are taxed favorably compared with apartments and carry no monthly maintenance or common charges, but they require consistent upkeep to protect their value.</p>
           </details>
           <details style={{ background: "#F9F6E6", border: "1px solid #E0D9B8", borderRadius: "16px", padding: "4px 26px" }}>
            <summary style={{ listStyle: "none", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "space-between", gap: "20px", padding: "20px 0", fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 19, color: "#0F1729" }}>What are the biggest maintenance costs?<span style={{ flex: "0 0 auto", color: "#C98A2C", fontSize: 24, lineHeight: "1" }}>+</span></summary>
            <p style={{ fontSize: 16, lineHeight: "1.8", color: "#3B4C5E", margin: "0 0 22px", textWrap: "pretty" }}>Facade restoration is often the largest, running up to $100,000 for major projects, followed by roof repairs, historic window care, and HVAC upgrades. Budgeting for a vetted team of contractors ahead of time keeps surprises manageable.</p>
           </details>
           <details style={{ background: "#F9F6E6", border: "1px solid #E0D9B8", borderRadius: "16px", padding: "4px 26px" }}>
            <summary style={{ listStyle: "none", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "space-between", gap: "20px", padding: "20px 0", fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 19, color: "#0F1729" }}>Do I need a specialized real estate agent?<span style={{ flex: "0 0 auto", color: "#C98A2C", fontSize: 24, lineHeight: "1" }}>+</span></summary>
            <p style={{ fontSize: 16, lineHeight: "1.8", color: "#3B4C5E", margin: "0 0 22px", textWrap: "pretty" }}>Yes. Brownstone and townhouse transactions involve landmark regulations, SRO conversions, and financing nuances that general agents rarely handle. Working with an advisor who focuses on this niche protects you through inspection, negotiation, and closing.</p>
           </details>
           <details style={{ background: "#F9F6E6", border: "1px solid #E0D9B8", borderRadius: "16px", padding: "4px 26px" }}>
            <summary style={{ listStyle: "none", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "space-between", gap: "20px", padding: "20px 0", fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 19, color: "#0F1729" }}>How long should I plan to own a brownstone?<span style={{ flex: "0 0 auto", color: "#C98A2C", fontSize: 24, lineHeight: "1" }}>+</span></summary>
            <p style={{ fontSize: 16, lineHeight: "1.8", color: "#3B4C5E", margin: "0 0 22px", textWrap: "pretty" }}>Plan for at least 10 years to justify the investment on a single-family home. If your horizon is shorter, a condo, co-op, or a 3 to 4 unit brownstone may make more financial sense.</p>
           </details>
          </div>

          <div style={{ margin: "48px 0 0", background: "#F5EECB", border: "1px solid #E0D9B8", borderLeft: "4px solid #C98A2C", borderRadius: "16px", padding: "30px 34px", display: "flex", alignItems: "center", justifyContent: "space-between", gap: "28px", flexWrap: "wrap" }}>
           <div style={{ flex: "1 1 340px" }}>
            <p style={{ fontSize: "16.5px", lineHeight: "1.7", color: "#0F1729", margin: 0, textWrap: "pretty" }}>If you're interested in selling or buying a brownstone in Manhattan, click the button to schedule a call, or email me at <a href="mailto:sm@montfortre.com" style={{ color: "#113B5F", borderBottom: "1px solid #C98A2C" }} {...{ "style-hover": "color:#C98A2C" }}>sm@montfortre.com</a>.</p>
           </div>
           <a href="https://calendly.com/montfort" style={{ flex: "0 0 auto", display: "inline-flex", alignItems: "center", justifyContent: "center", background: "#113B5F", color: "#F9F6E6", fontSize: "13.5px", fontWeight: "800", letterSpacing: "0.06em", textTransform: "uppercase", borderRadius: "100px", padding: "16px 28px", minHeight: 52 }} {...{ "style-hover": "background:#C98A2C; color:#0F1729" }}>Click Here to Schedule a Call</a>
          </div>

          <div style={{ display: "flex", flexWrap: "wrap", gap: "10px", marginTop: 22 }}>
           <a href="https://www.facebook.com/montfortrealestate" target="_blank" rel="noopener" style={{ display: "inline-flex", alignItems: "center", gap: "9px", background: "#113B5F", color: "#F9F6E6", fontSize: 12, fontWeight: "700", letterSpacing: "0.04em", borderRadius: "100px", padding: "11px 20px" }} {...{ "style-hover": "background:#C98A2C; color:#0F1729" }}><svg width="15" height="15" viewBox="0 0 24 24" fill="currentColor"><path d="M14 9h3V5.5h-3c-2.2 0-3.8 1.7-3.8 3.9V11H7.5v3.5h2.7V22h3.6v-7.5h2.7l.5-3.5h-3.2V9.6c0-.4.3-.6.7-.6z" /></svg>Facebook</a>
           <a href="https://twitter.com/intent/tweet?url=https://montfortre.com/advice-for-buyers-looking-to-purchase-brownstones/" target="_blank" rel="noopener" style={{ display: "inline-flex", alignItems: "center", gap: "9px", background: "#0F1729", color: "#F9F6E6", fontSize: 12, fontWeight: "700", letterSpacing: "0.04em", borderRadius: "100px", padding: "11px 20px" }} {...{ "style-hover": "background:#C98A2C; color:#0F1729" }}><svg width="13" height="13" viewBox="0 0 24 24" fill="currentColor"><path d="M18.9 2.3h3.3l-7.2 8.2 8.5 11.2h-6.6l-5.2-6.8-6 6.8H1.4l7.7-8.8L1 2.3h6.8l4.7 6.2 5.4-6.2zm-1.2 17.7h1.8L7.1 4.1H5.2l12.5 15.9z" /></svg>X</a>
           <a href="https://pinterest.com/pin/create/button/?url=https://montfortre.com/advice-for-buyers-looking-to-purchase-brownstones/" target="_blank" rel="noopener" style={{ display: "inline-flex", alignItems: "center", gap: "9px", background: "#B4141B", color: "#F9F6E6", fontSize: 12, fontWeight: "700", letterSpacing: "0.04em", borderRadius: "100px", padding: "11px 20px" }} {...{ "style-hover": "background:#C98A2C; color:#0F1729" }}><svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2C6.5 2 2 6.5 2 12c0 4.2 2.6 7.8 6.3 9.3-.1-.8-.2-2 0-2.9l1.2-5s-.3-.6-.3-1.5c0-1.4.8-2.5 1.9-2.5.9 0 1.3.7 1.3 1.5 0 .9-.6 2.2-.9 3.5-.2 1 .5 1.9 1.6 1.9 1.9 0 3.3-2 3.3-4.9 0-2.6-1.8-4.4-4.5-4.4-3 0-4.8 2.3-4.8 4.6 0 .9.3 1.9.8 2.4.1.1.1.2.1.3l-.3 1.2c0 .2-.2.2-.4.1-1.4-.6-2.2-2.7-2.2-4.3 0-3.5 2.6-6.8 7.4-6.8 3.9 0 6.9 2.8 6.9 6.5 0 3.9-2.4 7-5.9 7-1.2 0-2.3-.6-2.6-1.3l-.7 2.7c-.3 1-1 2.3-1.4 3 .9.3 1.8.4 2.8.4 5.5 0 10-4.5 10-10S17.5 2 12 2z" /></svg>Pinterest</a>
           <a href="https://www.linkedin.com/in/stanley-p-montfort-b3675548/" target="_blank" rel="noopener" style={{ display: "inline-flex", alignItems: "center", gap: "9px", background: "#1B5178", color: "#F9F6E6", fontSize: 12, fontWeight: "700", letterSpacing: "0.04em", borderRadius: "100px", padding: "11px 20px" }} {...{ "style-hover": "background:#C98A2C; color:#0F1729" }}><svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor"><path d="M6.5 8.5v10H3.3v-10h3.2zM4.9 3.5a1.85 1.85 0 1 1 0 3.7 1.85 1.85 0 0 1 0-3.7zM20.7 18.5h-3.2v-5.2c0-1.4-.5-2.3-1.7-2.3-.9 0-1.5.6-1.7 1.2-.1.2-.1.5-.1.8v5.5H10.7s.04-9 0-10h3.2v1.4c.4-.7 1.2-1.6 3-1.6 2.2 0 3.8 1.4 3.8 4.5v5.7z" /></svg>LinkedIn</a>
          </div>

          <div style={{ marginTop: 44, background: "#F9F6E6", border: "1px solid #E0D9B8", borderTop: "3px solid #C98A2C", borderRadius: "16px", padding: "34px 36px" }}>
           <div style={{ fontSize: "11.5px", fontWeight: "700", letterSpacing: "0.18em", textTransform: "uppercase", color: "#8A7B4E" }}>About the Author</div>
           <div style={{ display: "grid", gridTemplateColumns: "120px 1fr", gap: "28px", marginTop: 22, alignItems: "start" }}>
            <div style={{ width: 120, height: 120, borderRadius: "50%", overflow: "hidden", background: "#E0D9B8", border: "4px solid #FFFFFF", boxShadow: "0 16px 34px rgba(17,59,95,0.18)" }}><img src="/redesign-assets/stanley-portrait.webp" alt="Stanley Montfort" style={{ width: "100%", height: "100%", objectFit: "cover", objectPosition: "center 12%", display: "block" }} /></div>
            <div>
             <div style={{ fontFamily: "'Space Grotesk',system-ui,sans-serif", fontWeight: "700", fontSize: 22, letterSpacing: "-0.01em", color: "#0F1729" }}>Stanley Montfort<span style={{ fontWeight: "500", color: "#C98A2C" }}>, Real Estate Advisor®</span></div>
             <div style={{ display: "flex", flexDirection: "column", gap: "14px", marginTop: 16 }}>
              <p style={{ fontSize: "15.5px", lineHeight: "1.75", color: "#3B4C5E", margin: 0, textWrap: "pretty" }}>Since the start of the pandemic, Stanley Montfort has played a crucial role in facilitating over one billion dollars worth of brownstone sales in New York City. He is a recognized expert in the city's brownstone and townhouse market, with extensive experience in both sell-side and buy-side transactions, thanks to his military and law background.</p>
              <p style={{ fontSize: "15.5px", lineHeight: "1.75", color: "#3B4C5E", margin: 0, textWrap: "pretty" }}>Stanley honed his real estate skills at Leslie J. Garfield, where he established himself in the Harlem townhouse market and assisted in numerous co-ownership transactions, including more complicated deals involving SROs, seller financing, and negotiating with tenants, always leaving all parties satisfied.</p>
              <p style={{ fontSize: "15.5px", lineHeight: "1.75", color: "#3B4C5E", margin: 0, textWrap: "pretty" }}>With a vibrant, diversified career spanning the legal, banking, and technology industries, Stanley brings a wealth of experience to help clients achieve their real estate objectives. He applies innovative marketing, strategic thinking, and utmost professionalism and integrity to every deal. A savvy negotiator with strong analytical skills, he has navigated even the most challenging deals to deliver the desired results.</p>
              <p style={{ fontSize: "15.5px", lineHeight: "1.75", color: "#3B4C5E", margin: 0, textWrap: "pretty" }}>Moreover, Stanley provides a personalized, engaging experience marked by complete transparency, data-driven financial decisions, and honest conversations. He earns his clients' trust and is committed to ensuring their needs are fully understood and resolved without compromise.</p>
              <p style={{ fontSize: "15.5px", lineHeight: "1.75", color: "#3B4C5E", margin: 0, textWrap: "pretty" }}>Originally from New Jersey, Stanley is a graduate of Fordham University, where he earned his JD and a Master's in International Political Economy and Development. Stanley is the no-brainer choice to help you achieve your real estate goals.</p>
             </div>
             <div style={{ display: "flex", gap: "10px", marginTop: 20 }}>
              <a href="https://www.facebook.com/montfortrealestate" target="_blank" rel="noopener" aria-label="Facebook" style={{ width: 38, height: 38, borderRadius: "100px", background: "#C98A2C", color: "#0F1729", display: "flex", alignItems: "center", justifyContent: "center" }} {...{ "style-hover": "background:#113B5F; color:#F9F6E6" }}><svg width="15" height="15" viewBox="0 0 24 24" fill="currentColor"><path d="M14 9h3V5.5h-3c-2.2 0-3.8 1.7-3.8 3.9V11H7.5v3.5h2.7V22h3.6v-7.5h2.7l.5-3.5h-3.2V9.6c0-.4.3-.6.7-.6z" /></svg></a>
              <a href="https://www.instagram.com/stanleymontfort/" target="_blank" rel="noopener" aria-label="Instagram" style={{ width: 38, height: 38, borderRadius: "100px", background: "#C98A2C", color: "#0F1729", display: "flex", alignItems: "center", justifyContent: "center" }} {...{ "style-hover": "background:#113B5F; color:#F9F6E6" }}><svg width="14" height="14" viewBox="0 0 24 24" fill="none"><rect x="3" y="3" width="18" height="18" rx="5" stroke="currentColor" strokeWidth="1.9" /><circle cx="12" cy="12" r="4" stroke="currentColor" strokeWidth="1.9" /><circle cx="17.5" cy="6.5" r="1.3" fill="currentColor" /></svg></a>
              <a href="https://www.linkedin.com/in/stanley-p-montfort-b3675548/" target="_blank" rel="noopener" aria-label="LinkedIn" style={{ width: 38, height: 38, borderRadius: "100px", background: "#C98A2C", color: "#0F1729", display: "flex", alignItems: "center", justifyContent: "center" }} {...{ "style-hover": "background:#113B5F; color:#F9F6E6" }}><svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor"><path d="M6.5 8.5v10H3.3v-10h3.2zM4.9 3.5a1.85 1.85 0 1 1 0 3.7 1.85 1.85 0 0 1 0-3.7zM20.7 18.5h-3.2v-5.2c0-1.4-.5-2.3-1.7-2.3-.9 0-1.5.6-1.7 1.2-.1.2-.1.5-.1.8v5.5H10.7s.04-9 0-10h3.2v1.4c.4-.7 1.2-1.6 3-1.6 2.2 0 3.8 1.4 3.8 4.5v5.7z" /></svg></a>
              <a href="https://www.youtube.com/@montfortrealestate6984" target="_blank" rel="noopener" aria-label="YouTube" style={{ width: 38, height: 38, borderRadius: "100px", background: "#C98A2C", color: "#0F1729", display: "flex", alignItems: "center", justifyContent: "center" }} {...{ "style-hover": "background:#113B5F; color:#F9F6E6" }}><svg width="15" height="15" viewBox="0 0 24 24" fill="currentColor"><path d="M22 8.2a3 3 0 0 0-2.1-2.1C18 5.6 12 5.6 12 5.6s-6 0-7.9.5A3 3 0 0 0 2 8.2 31 31 0 0 0 1.7 12 31 31 0 0 0 2 15.8a3 3 0 0 0 2.1 2.1c1.9.5 7.9.5 7.9.5s6 0 7.9-.5a3 3 0 0 0 2.1-2.1c.3-1.3.3-3.8.3-3.8s0-2.5-.3-3.8zM10 15V9l5.2 3z" /></svg></a>
             </div>
            </div>
           </div>
          </div>
         </div>
        </div>
       </section>
      <ContactSection />
    </>
  );
}
